name: Update translate files

on:
  push:
    branches:
      - "master"
  repository_dispatch:
    types: [update_translate]
  schedule:
    - cron: "0 21 * * *"

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download translate file
        run: |
          curl -s -L ${{ secrets.TRANSLATE_URL }} | base64 -d > scripts.zip
          unzip -oq scripts.zip -d game/tl/Japanese/
          rm scripts.zip

      - name: Create Pull Request
        uses: proudust/create-pull-request@using-ssh
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deploy-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          commit-message: ":sparkles: 翻訳の更新"
          title: 翻訳の更新
          body: |
            この Pull Request は GitHub Actions により自動生成されています。
            毎朝 6 時に翻訳所から最新の翻訳が反映されます。
          assignees: proudust
          reviewers: proudust
          branch: translate
